### PR TITLE
Fix running command line with more than a single word under MSW

### LINKED ISSUE #18: `run` on Windows appears to escape quotes
_Originally posted by @vadz in https://github.com/tridactyl/tridactyl/issues/876#issuecomment-766111592_

There seems to be something wrong with command line parsing: my `editorcmd` is `gvim.exe -f -c "se ft=markdown wrap lbr tw=0" %f` and it worked fine with 0.1.10 before, but now it starts editing the file called `ft=markdown` and a few more because the quotes get escaped and I couldn't find any way to prevent this from happening (other than removing `-c ...` entirely). Would you have any idea about this by chance? TIA!

---

https://github.com/tridactyl/native_messenger/blob/100198fb4c1e5167ad59d310c93d4d3ef8e77ee8/src/native_main.nim#L108

### PR DESCRIPTION
**Pull request by vadz**
Use poEvalCommand under Windows too to ensure that commands containing
quotes are parsed correctly.

Prepend "cmd /c" to the full command to still allow using built-ins.

Closes #18.

---

Alternative, and simpler, fix replacing #20.

### CODE REVIEW

**Comment by bovine3dom** [comment]
Can you confirm that this isn't too much slower than the current master branch? You can test it with whatever the Windows equivalent of

```
time printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | env SHELL="/bin/sh" ./native_main
```

is : )

File: src/native_main.nim [hunk 1]
```diff
@@ -104,9 +104,11 @@ proc handleMessage(msg: MessageRecv): string =
                 reply.code = some(1)
 
         of "run":
-            var command = msg.command.get()
             when defined(windows):
```
Comment (bovine3dom) [inline src/native_main.nim:107]: `when` is a bit like an `#ifdef` so you can "declare things twice". With these changes `command` is immutable so in theory it'll be a bit quicker.

**Comment by vadz** [comment]
> 
> 
> Can you confirm that this isn't too much slower than the current master branch? You can test it with whatever the Windows equivalent of
> 
> ```
> time printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ./native_main
> ```
> 
> is : )

I've just run `path` command (`echo $PATH` would just output literal `$PATH` with cmd, which is probably not what you meant) in MSYS shell and I don't see any statistically significant difference in time.
